dbt_trino_capstone_2:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap
      user: "{{ env_var('TRINO_USERNAME') }}"
      password: "{{ env_var('TRINO_PASSWORD') }}"
      host: "{{ env_var('TRINO_IP_ADDRESS') }}"
      database: duckdb
      schema: staging
      port: 8443
      threads: 4
      http_scheme: https
