#!/bin/bash

curl -X POST http://localhost:8080/predict_cpk \
     -H "Content-Type: application/json" \
     -d '{
        "number_unique_values": 2,
        "count": 2,"is_unique": 1,
        "null_count": 0,
        "null_ratio": 0.0,
        "ordinal_position": 1,
        "unique_ratio": 1.0,
        "is_non_null": 1,
        "is_first_column": 1,
        "relative_ordinal_position": 0.3333333333333333,
        "is_first_unique_column": 1,
        "table_column_count": 3,
        "table_unique_column_count": 3,
        "table_row_count": 2,
        "other_unique_columns_in_table": 2,
        "table_has_unique_column": 1,
        "table_has_no_single_pk_candidate": 0,
        "table_near_unique_column_count": 3,
        "table_id_named_column_count": 1,
        "table_non_null_column_count": 3,
        "table_max_unique_ratio": 1.0,
        "table_integer_column_count": 1,
        "unique_ratio_rank": 1,
        "null_ratio_rank": 1,
        "is_least_null_in_table": 1,
        "unique_ratio_relative_to_max": 1.0,
        "other_near_unique_columns_in_table": 2,
        "name_ends_with_id": 0,
        "name_contains_key": 0,
        "name_contains_table_name": 1,
        "name_is_singular_table_id": 0,
        "name_length": 12,
        "column_type_boolean": false,
        "column_type_date": false,
        "column_type_decimal": false,
        "column_type_double": false,
        "column_type_integer": true,
        "column_type_varchar": false
    }'
