version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: mlflow_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
  mc:
    image: minio/mc:latest
    container_name: mlflow_init_bucket
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword;
      /usr/bin/mc mb --ignore-existing myminio/mlflow;
      /usr/bin/mc mb --ignore-existing myminio/postgres-backups;
      exit 0;
      "

  postgres:
    image: postgres:15-alpine
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow_user -d mlflow_db"]
      interval: 5s
      timeout: 5s
      retries: 3


  postgres_backup:
    image: eeshugerman/postgres-backup-s3:15
    container_name: mlflow_postgres_backup
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadminpassword
      - S3_BUCKET=postgres-backups
      - S3_ENDPOINT=http://minio:9000
      - S3_S3V4=yes
      - S3_PREFIX=mlflow_db_backups
      - S3_REGION=eu-central-1
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password
      - POSTGRES_DB=mlflow_db
      - POSTGRES_DATABASE=mlflow_db
      - SCHEDULE=@hourly 
      - BACKUP_KEEP_DAYS=30

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadminpassword
      - AWS_DEFAULT_REGION=eu-central-1
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_S3_IGNORE_TLS=true
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow_db
      --default-artifact-root s3://mlflow/ 
      --host 0.0.0.0 
      --port 5000

volumes:
  minio_data:
  postgres_data:
